word_list = [
    "Apple",
    "Application",
    "Account",
    "Action",
    "Active",
    "Address",
    "Advanced",
    "Adventure",
    "Agency",
    "Algorithm",
    "Alpha",
    "Analysis",
    "Animation",
    "Annual",
    "Answer",
    "Anthem",
    "Appeal",
    "Applied",
    "Approach",
    "Area",
    "Argument",
    "Array",
    "Arrow",
    "Artist",
    "Assembly",
    "Asset",
    "Assign",
    "Atlas",
    "Atomic",
    "Attack",
    "Attempt",
    "Attitude",
    "Audio",
    "Award",
    "Backend",
    "Balance",
    "Bandwidth",
    "Base",
    "Basis",
    "Beauty",
    "Behavior",
    "Beta",
    "Binary",
    "Biology",
    "Blade",
    "Bond",
    "Boot",
    "Boundary",
    "Breadth",
    "Bridge",
    "Brief",
    "Broad",
    "Browser",
    "Budget",
    "Buffer",
    "Bug",
    "Build",
    "Bulk",
    "Button",
    "Byte",
    "Cache",
    "Calculate",
    "Capability",
    "Capacity",
    "Capital",
    "Capture",
    "Career",
    "Category",
    "Cause",
    "Central",
    "Century",
    "Chain",
    "Channel",
    "Chapter",
    "Charge",
    "Chart",
    "Check",
    "Chief",
    "Choice",
    "Circle",
    "Class",
    "Client",
    "Climate",
    "Cluster",
    "Code",
    "Collaborate",
    "Collection",
    "Color",
    "Column",
    "Combat",
    "Comfort",
    "Command",
    "Comment",
    "Commit",
    "Common",
    "Community",
    "Company",
    "Compare",
    "Compile",
    "Complete",
    "Component",
    "Compose",
    "Compute",
    "Concept",
    "Conduct",
    "Connect",
    "Console",
    "Constant",
    "Construct",
    "Contact",
    "Contain",
    "Content",
    "Context",
    "Contract",
    "Control",
    "Convert",
    "Copy",
    "Core",
    "Corner",
    "Correct",
    "Count",
    "Course",
    "Cover",
    "Create",
    "Credit",
    "Critical",
    "Crop",
    "Cross",
    "Culture",
    "Current",
    "Curve",
    "Custom",
    "Cycle",
    "Damage",
    "Danger",
    "Dark",
    "Data",
    "Debug",
    "Decide",
    "Default",
    "Define",
    "Delay",
    "Delete",
    "Demand",
    "Deploy",
    "Depth",
    "Design",
    "Detail",
    "Develop",
    "Device",
    "Dialog",
    "Direct",
    "Directory",
    "Disable",
    "Display",
    "Distance",
    "Distinct",
    "Distribute",
    "Divide",
    "Document",
    "Domain",
    "Download",
    "Draft",
    "Drag",
    "Draw",
    "Driver",
    "Drop",
    "Duration",
    "Dynamic",
    "Echo",
    "Edge",
    "Edit",
    "Effect",
    "Element",
    "Enable",
    "End",
    "Energy",
    "Engine",
    "Entity",
    "Entry",
    "Environment",
    "Equal",
    "Equip",
    "Error",
    "Event",
    "Example",
    "Exchange",
    "Exclude",
    "Execute",
    "Exist",
    "Exit",
    "Expand",
    "Expect",
    "Expert",
    "Export",
    "Extend",
    "External",
    "Extract",
    "Factor",
    "Failure",
    "Feature",
    "Field",
    "File",
    "Filter",
    "Final",
    "Finish",
    "First",
    "Fixed",
    "Flag",
    "Flash",
    "Flow",
    "Focus",
    "Folder",
    "Follow",
    "Force",
    "Form",
    "Format",
    "Forward",
    "Frame",
    "Free",
    "Frequency",
    "Front",
    "Function",
    "Future",
    "Gain",
    "Game",
    "Gap",
    "Gateway",
    "General",
    "Generate",
    "Global",
    "Goal",
    "Grade",
    "Graph",
    "Grid",
    "Group",
    "Growth",
    "Guide",
    "Hard",
    "Hardware",
    "Header",
    "Health",
    "Heavy",
    "Height",
    "Help",
    "Hierarchy",
    "Highlight",
    "Hold",
    "Horizontal",
    "Host",
    "Idea",
    "Image",
    "Impact",
    "Import",
    "Index",
    "Infinite",
    "Initial",
    "Inject",
    "Innovation",
    "Input",
    "Insert",
    "Instance",
    "Interface",
    "Internal",
    "Internet",
    "Interpret",
    "Introduce",
    "Invent",
    "Invert",
    "Invest",
    "Invoke",
    "Iteration",
    "Join",
    "Journal",
    "Judgment",
    "Jump",
    "Justify",
    "Keep",
    "Key",
    "Keyword",
    "Label",
    "Layer",
    "Layout",
    "Leader",
    "Learning",
    "Legacy",
    "Legal",
    "Length",
    "Library",
    "License",
    "Limit",
    "Linear",
    "Link",
    "Load",
    "Logic",
    "Logistic",
    "Loop",
    "Machine",
    "Main",
    "Manage",
    "Manual",
    "Map",
    "Margin",
    "Market",
    "Match",
    "Material",
    "Matrix",
    "Mature",
    "Max",
    "Measure",
    "Medium",
    "Member",
    "Memory",
    "Menu",
    "Merge",
    "Message",
    "Method",
    "Metrics",
    "Middle",
    "Migration",
    "Mile",
    "Mind",
    "Minor",
    "Mode",
    "Model",
    "Modify",
    "Module",
    "Monitor",
    "Mount",
    "Move",
    "Multiple",
    "Name",
    "Native",
    "Natural",
    "Navigate",
    "Network",
    "Neutral",
    "Node",
    "Noise",
    "Normal",
    "Note",
    "Notify",
    "Number",
    "Object",
    "Observ",
    "Obtain",
    "Occur",
    "Offer",
    "Offset",
    "Online",
    "Open",
    "Operate",
    "Opinion",
    "Option",
    "Order",
    "Origin",
    "Output",
    "Overall",
    "Own",
    "Package",
    "Page",
    "Panel",
    "Parent",
    "Parse",
    "Partial",
    "Pass",
    "Pattern",
    "Pause",
    "Peak",
    "Period",
    "Permission",
    "Phase",
    "Pick",
    "Pilot",
    "Place",
    "Plain",
    "Plan",
    "Platform",
    "Plugin",
    "Policy",
    "Pool",
    "Port",
    "Position",
    "Positive",
    "Post",
    "Potential",
    "Power",
    "Practice",
    "Prefix",
    "Press",
    "Preview",
    "Primary",
    "Print",
    "Priority",
    "Private",
    "Process",
    "Produce",
    "Profile",
    "Program",
    "Project",
    "Protect",
    "Protocol",
    "Provide",
    "Public",
    "Publish",
    "Pull",
    "Purchase",
    "Purple",
    "Purpose",
    "Push",
    "Python",
    "Quality",
    "Quantity",
    "Query",
    "Queue",
    "Quick",
    "Random",
    "Range",
    "Rate",
    "Read",
    "Ready",
    "Reality",
    "Reason",
    "Receive",
    "Recent",
    "Recognize",
    "Record",
    "Recover",
    "Reduce",
    "Refer",
    "Refine",
    "Register",
    "Regular",
    "Reject",
    "Release",
    "Remain",
    "Remote",
    "Remove",
    "Render",
    "Repeat",
    "Replace",
    "Reply",
    "Report",
    "Request",
    "Reserve",
    "Reset",
    "Resolve",
    "Resource",
    "Respond",
    "Restore",
    "Result",
    "Retain",
    "Retrieve",
    "Return",
    "Reverse",
    "Review",
    "Revolution",
    "Rights",
    "Ring",
    "Rise",
    "Role",
    "Route",
    "Rule",
    "Safe",
    "Save",
    "Scale",
    "Scan",
    "Schedule",
    "Scheme",
    "Screen",
    "Script",
    "Search",
    "Secure",
    "Select",
    "Self",
    "Sequence",
    "Service",
    "Session",
    "Setting",
    "Shadow",
    "Shape",
    "Share",
    "Shift",
    "Short",
    "Show",
    "Signal",
    "Simple",
    "Simulate",
    "Single",
    "Site",
    "Size",
    "Skill",
    "Smart",
    "Software",
    "Solution",
    "Source",
    "Space"
]
sym_list = [
    "_",
    "-",
    "/"
    "."
]
names_en_male = [
    "James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas", "Charles",
    "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua",
    "Kenneth", "Kevin", "Brian", "George", "Timothy", "Ronald", "Edward", "Jason", "Jeffrey", "Ryan",
    "Jacob", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott", "Brandon",
    "Benjamin", "Samuel", "Raymond", "Gregory", "Frank", "Alexander", "Patrick", "Jack", "Dennis", "Jerry",
    "Tyler", "Aaron", "Jose", "Nathan", "Adam", "Henry", "Zachary", "Todd", "Walter", "Kyle",
    "Carl", "Arthur", "Harry", "Ethan", "Noah", "Liam", "Mason", "Logan", "Oliver", "Elijah",
    "Carter", "Grayson", "Jayden", "Dylan", "Luke", "Gabriel", "Anthony", "Isaac", "Owen", "Caleb",
    "Hunter", "Cameron", "Evan", "Adrian", "Aiden", "Brayden", "Hayden", "Julian", "Max", "Leo",
    "Jaxon", "Eli", "Cooper", "Chase", "Blake", "Spencer", "Derek", "Trevor", "Brett", "Shawn"
]
names_de_male = [
    "Hans", "Peter", "Klaus", "Dieter", "Heinz", "Günter", "Karl", "Jürgen", "Bernd", "Manfred",
    "Andreas", "Thomas", "Michael", "Stefan", "Wolfgang", "Werner", "Horst", "Uwe", "Rainer", "Rolf",
    "Volker", "Gerhard", "Gerd", "Ernst", "Helmut", "Otto", "Hermann", "Friedrich", "Wilhelm", "Ludwig",
    "Franz", "Josef", "Fritz", "Heinrich", "Alfred", "Walter", "Kurt", "Leo", "Maximilian", "Lukas",
    "Felix", "Tobias", "Julian", "Elias", "Niklas", "Lennart", "Jonas", "Paul", "Emil", "Moritz",
    "Bastian", "Finn", "Levi", "Mika", "Oskar", "Theo", "Matthias", "Johannes", "Christian", "Daniel",
    "Florian", "Patrick", "Marcel", "Sven", "Erik", "Heiko", "Jens", "Carsten", "Thorsten", "Gunnar",
    "Ingo", "Armin", "Berthold", "Eberhard", "Gustav", "Alois", "Kaspar", "Nico", "Till", "Benno"
]
names_ru_male = [
    "Александр", "Сергей", "Дмитрий", "Андрей", "Алексей", "Михаил", "Иван", "Николай", "Владимир", "Виктор",
    "Евгений", "Антон", "Григорий", "Георгий", "Илья", "Константин", "Лев", "Леонид", "Матвей", "Максим",
    "Артем", "Денис", "Егор", "Захар", "Кирилл", "Мирон", "Никита", "Олег", "Павел", "Роман",
    "Станислав", "Тимофей", "Федор", "Юрий", "Ярослав", "Анатолий", "Борис", "Вадим", "Валентин", "Валерий",
    "Виталий", "Владислав", "Вячеслав", "Геннадий", "Глеб", "Даниил", "Елисей", "Игорь", "Макар", "Назар",
    "Платон", "Радислав", "Родион", "Ростислав", "Савелий", "Семен", "Святослав", "Тарас", "Тихон", "Филипп",
    "Эдуард", "Юлиан", "Яков", "Аркадий", "Арсений", "Богдан", "Всеволод", "Гавриил", "Герман", "Давид",
    "Еремей", "Зиновий", "Изяслав", "Иосиф", "Кузьма", "Лука", "Модест", "Наум", "Прохор", "Степан"
]
names_fr_male = [
    "Jean", "Pierre", "Louis", "François", "Jacques", "Philippe", "Charles", "Denis", "Michel", "André",
    "Antoine", "Bernard", "Bruno", "Christian", "Claude", "Daniel", "David", "Éric", "Fabien", "Gabriel",
    "Georges", "Guillaume", "Henri", "Hugo", "Jean-Luc", "Julien", "Laurent", "Lucas", "Marc", "Marcel",
    "Martin", "Mathieu", "Matthieu", "Maxime", "Nicolas", "Olivier", "Patrick", "Paul", "Raymond", "René",
    "Robert", "Roger", "Romain", "Samuel", "Sébastien", "Thibault", "Thomas", "Valentin", "Vincent", "Xavier",
    "Adrien", "Alexandre", "Amaury", "Bastien", "Benoît", "Cédric", "Cyril", "Damien", "Émile", "Eugène",
    "Florent", "Gaël", "Gérard", "Gilles", "Hervé", "Joachim", "Jules", "Léandre", "Léon", "Loïc",
    "Lucien", "Maurice", "Noël", "Pascal", "Raoul", "Raphaël", "Rémy", "Renan", "Roch", "Théo"
]
names_es_male = [
    "José", "Juan", "Antonio", "Manuel", "Francisco", "Jesús", "Javier", "Carlos", "David", "Alejandro",
    "Jorge", "Luis", "Miguel", "Pedro", "Pablo", "Rafael", "Ángel", "Daniel", "Sergio", "Fernando",
    "Adrián", "Alberto", "Alfredo", "Andrés", "Arturo", "Augusto", "Bernardo", "Camilo", "César", "Cristian",
    "Diego", "Eduardo", "Emilio", "Enrique", "Esteban", "Eugenio", "Felipe", "Félix", "Gabriel", "Gerardo",
    "Gonzalo", "Guillermo", "Héctor", "Hugo", "Ignacio", "Iván", "Jaime", "Joaquín", "Julián", "Leonardo",
    "Lorenzo", "Marco", "Marcos", "Mario", "Mateo", "Mauro", "Nicolás", "Óscar", "Patricio", "Raúl",
    "Ricardo", "Roberto", "Rodrigo", "Rubén", "Salvador", "Samuel", "Santiago", "Sebastián", "Tomás", "Vicente"
]
names_it_male = [
    "Marco", "Alessandro", "Giuseppe", "Francesco", "Luca", "Andrea", "Matteo", "Antonio", "Giovanni", "Stefano",
    "Lorenzo", "Michele", "Daniele", "Roberto", "Paolo", "Simone", "Federico", "Dario", "Mario", "Luigi",
    "Enrico", "Franco", "Sergio", "Alberto", "Claudio", "Emiliano", "Emanuele", "Gianluca", "Riccardo", "Nicola",
    "Fabio", "Massimo", "Giorgio", "Davide", "Pietro", "Ettore", "Felice", "Giacomo", "Gianni", "Guido",
    "Leonardo", "Mauro", "Mirco", "Oscar", "Pasquale", "Piero", "Raffaele", "Renato", "Salvatore", "Silvio",
    "Tommaso", "Valentino", "Valerio", "Vincenzo", "Vittorio", "Aldo", "Armando", "Bruno", "Carlo", "Cesare",
    "Dino", "Elio", "Eugenio", "Fabrizio", "Filippo", "Fulvio", "Gino", "Giulio", "Ivano", "Lamberto"
]
names_sc_male = [
    "Erik", "Anders", "Johan", "Lars", "Nils", "Per", "Sven", "Karl", "Magnus", "Olof",
    "Gustav", "Henrik", "Fredrik", "Mikael", "Christian", "Peter", "Jens", "Thomas", "Morten", "Martin",
    "Lars", "Jørgen", "Mads", "Søren", "Rasmus", "Emil", "Noah", "William", "Oliver", "Oscar",
    "Axel", "Elias", "Hugo", "Isak", "Liam", "August", "Ebbe", "Felix", "Gunnar", "Håkan",
    "Ingvar", "Jesper", "Jonas", "Kjell", "Leif", "Mats", "Niklas", "Ove", "Patrik", "Rolf",
    "Stig", "Tomas", "Ulf", "Viggo", "Viktor", "Arne", "Bengt", "Björn", "Claes", "Dan",
    "Elof", "Erling", "Finn", "Göran", "Hannes", "Ivar", "Jan", "Kent", "Lennart", "Ola"
]
names_en_female = [
    "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Jessica", "Sarah", "Karen",
    "Lisa", "Nancy", "Betty", "Helen", "Sandra", "Donna", "Carol", "Ruth", "Sharon", "Michelle",
    "Laura", "Sarah", "Kimberly", "Deborah", "Jessica", "Amy", "Angela", "Melissa", "Brenda", "Anna",
    "Rebecca", "Virginia", "Kathleen", "Pamela", "Martha", "Debra", "Amanda", "Stephanie", "Carolyn", "Christine",
    "Marie", "Janet", "Catherine", "Frances", "Ann", "Joyce", "Diane", "Alice", "Julie", "Heather",
    "Teresa", "Doris", "Gloria", "Evelyn", "Jean", "Cheryl", "Mildred", "Katherine", "Joan", "Ashley",
    "Judith", "Rose", "Janice", "Kelly", "Nicole", "Judy", "Christina", "Kathy", "Theresa", "Beverly",
    "Denise", "Tammy", "Irene", "Jane", "Lori", "Rachel", "Marilyn", "Andrea", "Kathryn", "Louise",
    "Sara", "Anne", "Jacqueline", "Wanda", "Bonnie", "Julia", "Ruby", "Lois", "Tina", "Phyllis"
]
names_de_female = [
    "Anna", "Maria", "Ursula", "Elisabeth", "Monika", "Sabine", "Andrea", "Petra", "Martina", "Christina",
    "Karin", "Claudia", "Susanne", "Brigitte", "Gisela", "Ingrid", "Erika", "Heike", "Angelika", "Renate",
    "Gertrud", "Hildegard", "Elena", "Annika", "Julia", "Laura", "Lena", "Mia", "Hannah", "Sophie",
    "Martha", "Emma", "Ella", "Greta", "Ida", "Lilli", "Paula", "Thea", "Tilda", "Frieda",
    "Anita", "Bertha", "Dora", "Elsa", "Frida", "Gabi", "Heidi", "Ilse", "Johanna", "Katharina",
    "Lea", "Lotte", "Magda", "Nora", "Olga", "Rosa", "Sofia", "Vera", "Wilma", "Zita",
    "Anke", "Dagmar", "Edith", "Grete", "Helga", "Irmgard", "Liesel", "Marlene", "Ruth", "Silke",
    "Tanja", "Ulrike", "Viola", "Waltraud", "Annegret", "Elke", "Gudrun", "Hannelore", "Jutta", "Kirsten"
]
names_ru_female = [
    "Екатерина", "Ольга", "Анна", "Мария", "Елена", "Наталья", "Светлана", "Ирина", "Татьяна", "Анастасия",
    "Виктория", "Юлия", "Ксения", "Дарья", "Александра", "Надежда", "Алина", "Инна", "Людмила", "Галина",
    "Лариса", "Маргарита", "Полина", "Валентина", "Вера", "Зоя", "Лидия", "Раиса", "Регина", "Тамара",
    "Алла", "Диана", "Евгения", "Жанна", "Зинаида", "Карина", "Лилия", "Майя", "Нина", "Оксана",
    "Рита", "Снежана", "София", "Ульяна", "Фаина", "Эмилия", "Яна", "Аделина", "Алиса", "Амелия",
    "Богдана", "Валерия", "Василиса", "Виолетта", "Владислава", "Ева", "Елизавета", "Иванна", "Капитолина", "Клавдия",
    "Любовь", "Марина", "Милана", "Наталия", "Нелли", "Олеся", "Прасковья", "Руслана", "Серафима", "Станислава",
    "Стефания", "Таисия", "Федосья", "Эльвира", "Юнона", "Аврора", "Агата", "Агния", "Анжела", "Антонина"
]
names_fr_female = [
    "Marie", "Jeanne", "Françoise", "Catherine", "Monique", "Nicole", "Christine", "Martine", "Claudine", "Sylvie",
    "Anne", "Isabelle", "Nathalie", "Danielle", "Suzanne", "Jacqueline", "Bernadette", "Lucie", "Pauline", "Madeleine",
    "Marguerite", "Adeline", "Agnès", "Amélie", "Aurore", "Brigitte", "Cécile", "Chloé", "Claire", "Coline",
    "Élisabeth", "Élise", "Elodie", "Émilie", "Emma", "Eugénie", "Fleur", "Gabrielle", "Geneviève", "Hélène",
    "Honorine", "Inès", "Irène", "Juliette", "Justine", "Léa", "Léonie", "Liliane", "Lise", "Lorraine",
    "Louise", "Lucienne", "Manon", "Marcelle", "Margaux", "Marion", "Mélanie", "Micheline", "Mireille", "Noëlle",
    "Odette", "Pascale", "Perrine", "Renée", "Rolande", "Rosalie", "Rose", "Sabine", "Sandrine", "Sophie"
]
names_es_female = [
    "María", "Carmen", "Josefa", "Ana", "Isabel", "Dolores", "Teresa", "Rosa", "Antonia", "Francisca",
    "Juana", "Laura", "Mercedes", "Manuela", "Pilar", "Cristina", "Elena", "Silvia", "Sara", "Raquel",
    "Marta", "Paula", "Lucía", "Alicia", "Natalia", "Patricia", "Sandra", "Eva", "Adriana", "Alba",
    "Andrea", "Angeles", "Beatriz", "Carolina", "Clara", "Diana", "Emilia", "Esther", "Eugenia", "Felisa",
    "Gabriela", "Gloria", "Inés", "Irene", "Julia", "Lorena", "Luisa", "Marina", "Noelia", "Olivia",
    "Pablo", "Paloma", "Rocío", "Ruth", "Salud", "Soledad", "Sonia", "Susana", "Valeria", "Verónica",
    "Violeta", "Yolanda", "Alejandra", "Amparo", "Ángela", "Aurora", "Azucena", "Bárbara", "Belén", "Blanca",
    "Concepción", "Consuelo", "Dulce", "Elisa", "Encarnación", "Esperanza", "Graciela", "Guadalupe", "Herminia", "Lidia"
]
names_it_female = [
    "Maria", "Anna", "Giuseppe", "Francesca", "Rosa", "Giuseppina", "Lucia", "Angela", "Antonia", "Elena",
    "Teresa", "Giovanna", "Paola", "Laura", "Sara", "Valentina", "Martina", "Chiara", "Alessandra", "Silvia",
    "Daniela", "Simona", "Monica", "Stefania", "Federica", "Caterina", "Margherita", "Giorgia", "Alice", "Elisa",
    "Marta", "Emma", "Ginevra", "Beatrice", "Bianca", "Camilla", "Diana", "Diletta", "Eleonora", "Emanuela",
    "Fabiola", "Fiamma", "Fiorella", "Flavia", "Gabriella", "Gaia", "Gianna", "Gina", "Grazia", "Ilaria",
    "Irene", "Livia", "Ludovica", "Luisa", "Mara", "Marina", "Melissa", "Micaela", "Nadia", "Nicoletta",
    "Noemi", "Oriana", "Patrizia", "Pierina", "Raffaella", "Renata", "Rita", "Roberta", "Romina", "Sabrina",
    "Serena", "Silvana", "Sofia", "Tania", "Vanessa", "Vera", "Veronica", "Vincenza", "Viola", "Virginia"
]
names_sc_female = [
    "Anna", "Maria", "Elin", "Karin", "Kristina", "Lena", "Margareta", "Eva", "Birgitta", "Sara",
    "Emma", "Ida", "Julia", "Maja", "Clara", "Elsa", "Ebba", "Greta", "Hanna", "Lovisa",
    "Nora", "Olivia", "Alice", "Astrid", "Eleonora", "Ester", "Hilma", "Ingrid", "Linnea", "Matilda",
    "Signe", "Sofie", "Vendela", "Vera", "Alma", "Amalia", "Augusta", "Beata", "Bernhardina", "Britta",
    "Cecilia", "Dagny", "Disa", "Edit", "Eivor", "Ellen", "Elvira", "Emmy", "Frida", "Gertrud",
    "Gunilla", "Gunvor", "Hedvig", "Helena", "Hermine", "Hilda", "Inga", "Irma", "Johanna", "Josefina",
    "Julia", "Kajsa", "Kristin", "Laila", "Lilly", "Lina", "Malin", "Mona", "Nina", "Ottilia",
    "Petra", "Ragnhild", "Rebecca", "Rut", "Saga", "Sigrid", "Siv", "Solveig", "Stina", "Svea"
]
all_names = (
    names_en_male + names_de_male + names_ru_male + names_fr_male + 
    names_es_male + names_it_male + names_sc_male +
    names_en_female + names_de_female + names_ru_female + names_fr_female +
    names_es_female + names_it_female + names_sc_female
)